root = "."
tmp_dir = "/app/build"

[build]
cmd = "go build -o /app/build/main ."
bin = "/app/build/main"
include_ext = ["go", "html"]
exclude_dir = ["build"]
delay = 1000 # ms

[log]
time = true

[screen]
clear_on_rebuild = true 