services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POMELO_MODE=insecure
    tty: true
    depends_on:
      - db

  web-internal:
    build: .
    ports:
      - "8080"
    env_file:
      - .env
    environment:
      - POMELO_MODE=secure
    tty: true
    depends_on:
      - db

  modsecurity:
    build:
      context: .
      dockerfile: Dockerfile.modsecurity
    ports:
      - "8081:8080"
    environment:
      - PROXY_SSL=off
      - PARANOIA=1
      - SERVER_NAME=modsecurity
      - BACKEND=http://web-internal:8080
      - MODSEC_RULE_ENGINE=on
      - MODSEC_AUDIT_LOG=/dev/stdout
      - MODSEC_AUDIT_LOG_FORMAT=JSON
      - MODSEC_AUDIT_LOG_TYPE=Serial
      - MODSEC_AUDIT_LOG_PARTS=ABIJDEFHZ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 4s
    depends_on:
      - web

  db:
    image: postgres:16
    env_file:
      - .env  
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 