services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    # Enable hot reload
    deploy:
      restart_policy:
        condition: on-failure
    # Keep container running even if the app crashes
    tty: true
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - .env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 