services:
  modsecurity:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8081:8080"
    environment:
      - PROXY_SSL=off
      - PARANOIA=1
      - SERVER_NAME=modsecurity
      - BACKEND=http://web:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 4s

  web:
    build: .
    ports:
      - "8080:3000"
    expose:
      - "3001"
    environment:
      - INSECURE_PORT=3000
      - SECURE_PORT=3001
    volumes:
      - .:/app
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
    tty: true
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - .env  
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 